// <auto-generated />
using System;
using Assetra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assetra.Migrations
{
    [DbContext(typeof(AssetraContext))]
    [Migration("20260821065730_AddConditionMonitoring")]
    partial class AddConditionMonitoring
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Assetra.Models.ConditionHistory", b =>
                {
                    b.Property<int>("ConditionHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ConditionHistoryId"));

                    b.Property<string>("ConditionStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateRecorded")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<string>("PropertyId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RecordedBy")
                        .HasColumnType("longtext");

                    b.HasKey("ConditionHistoryId");

                    b.HasIndex("PropertyId");

                    b.ToTable("ConditionHistories");
                });

            modelBuilder.Entity("Assetra.Models.ConditionReport", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<string>("Condition")
                        .HasColumnType("longtext");

                    b.Property<string>("CustodianRemarks")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DateReviewed")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateSubmitted")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsScheduled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("LendingId")
                        .HasColumnType("int");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("longtext");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext");

                    b.Property<int?>("ReportNumber")
                        .HasColumnType("int");

                    b.Property<string>("ReviewedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ScheduledDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ReportId");

                    b.HasIndex("LendingId");

                    b.ToTable("ConditionReports");
                });

            modelBuilder.Entity("Assetra.Models.LendingRecord", b =>
                {
                    b.Property<int>("LendingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LendingId"));

                    b.Property<int?>("BorrowedBy")
                        .HasColumnType("int");

                    b.Property<string>("BorrowedCondition")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BorrowerName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateBorrowed")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateReturned")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ProcessedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("PropertyId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ReturnedCondition")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StudentId")
                        .HasColumnType("longtext");

                    b.HasKey("LendingId");

                    b.HasIndex("BorrowedBy");

                    b.HasIndex("PropertyId");

                    b.ToTable("LendingRecords");
                });

            modelBuilder.Entity("Assetra.Models.MaintenanceRecord", b =>
                {
                    b.Property<int>("MaintenanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaintenanceId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PropertyId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MaintenanceId");

                    b.HasIndex("PropertyId");

                    b.ToTable("MaintenanceRecords");
                });

            modelBuilder.Entity("Assetra.Models.Property", b =>
                {
                    b.Property<string>("PropertyId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ConditionStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("QrCodePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PropertyId");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("Assetra.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Assetra.Models.ConditionHistory", b =>
                {
                    b.HasOne("Assetra.Models.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("Assetra.Models.ConditionReport", b =>
                {
                    b.HasOne("Assetra.Models.LendingRecord", "Lending")
                        .WithMany()
                        .HasForeignKey("LendingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lending");
                });

            modelBuilder.Entity("Assetra.Models.LendingRecord", b =>
                {
                    b.HasOne("Assetra.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("BorrowedBy");

                    b.HasOne("Assetra.Models.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Assetra.Models.MaintenanceRecord", b =>
                {
                    b.HasOne("Assetra.Models.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });
#pragma warning restore 612, 618
        }
    }
}
